### PR TITLE
Enable IP customization using DHCP

### PR DESCRIPTION
**Pull request by cattywampus**
## Description

This changes updates the `CustomizationSpec` applied to the cloned VM so
that it's IP address can be generated automatically using DHCP if a
fixed IPv4 address is not specified. To make this possible the
validations on the guest customization settings had to be adjusted to
allow `ip_address`, `subnet_mask`, and `gateway` to be optional instead
of required. Now if the `ip_address` is omitted the VM's customization
spec will use the `CustomizationDhcpIpGenerator` when setting up the
customized ip settings.

I tested this by:
- [x] specifying a fixed IP address
- [x] removing the `ip_address`, `gateway`, and `subnet` and successfully leased a DHCP address

Signed-off-by: Keith Walters <kwalters@taphere.com>

## Related Issue

Issue #109 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] I have run the pre-merge tests locally and they pass.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

### CODE REVIEW

**Comment by mkennedy85** [comment]
Thanks for the contribution. Looks great and looking forward to leveraging this functionality as well.

**Comment by mekhanique** [comment]
Would love to see this merged/released soon.  We could really use it!

**Comment by Belogix** [comment]
I am basing some changes off of this, and adding Windows support too (will raise PR in due course). For what it is worth this PR works with my Linux builds and DHCP too, so using it locally until this PR is merged.

**Comment by cattywampus** [comment]
Thanks @clintoncwolfe. I was able to test it with a static IP address, should have mentioned this in the description (will update). 

I'm new to the RbVmomi API. Still kind of feeling my way around and having trouble finding a good source of documentation. My best source of reference for what it provides and how it's used has been the no longer supported [chef-provisioning-vsphere](https://github.com/chef-boneyard/chef-provisioning-vsphere/blob/master/lib/chef/provisioning/vsphere_driver/clone_spec_builder.rb#L130) gem.

**Comment by mkennedy85** [comment]
@cattywampus you may have found and used this, but I primarily relied on https://github.com/vmware/vsphere-automation-sdk-ruby/tree/master/vcenter for the changes with Guest OS customization.

**Comment by mkennedy85** [comment]
@cattywampus actually I apologize as I previously shared the incorrect link. Misplacing my resources these days. The VIM operations map to Managed and Data objects in https://code.vmware.com/apis/196/vsphere/doc/. Still new to it, but that was my resources.

**Review by marcparadise — APPROVED** [review]

**Pull request merged**
